using System.Collections.Generic;
using Wookashi.ExtraText.Normalize.Enums;

namespace Wookashi.ExtraText.Normalize.Models
{
    internal sealed class LanguageDiacriticalMark
    {
        public Language Language { get; }
        public string Source { get; }
        public string Target { get; }

        private LanguageDiacriticalMark(Language language, string source, string target)
        {
            Language = language;
            Source = source;
            Target = target;
        }

        internal static IEnumerable<LanguageDiacriticalMark> Marks => new List<LanguageDiacriticalMark>
        {
            // Polish
            new LanguageDiacriticalMark(Language.Polish, "ą", "a"),
            new LanguageDiacriticalMark(Language.Polish, "ć", "c"),
            new LanguageDiacriticalMark(Language.Polish, "ę", "e"),
            new LanguageDiacriticalMark(Language.Polish, "ł", "l"),
            new LanguageDiacriticalMark(Language.Polish, "ń", "n"),
            new LanguageDiacriticalMark(Language.Polish, "ó", "o"),
            new LanguageDiacriticalMark(Language.Polish, "ś", "s"),
            new LanguageDiacriticalMark(Language.Polish, "ź", "z"),
            new LanguageDiacriticalMark(Language.Polish, "ż", "z"),
            new LanguageDiacriticalMark(Language.Polish, "Ą", "A"),
            new LanguageDiacriticalMark(Language.Polish, "Ć", "C"),
            new LanguageDiacriticalMark(Language.Polish, "Ę", "E"),
            new LanguageDiacriticalMark(Language.Polish, "Ł", "L"),
            new LanguageDiacriticalMark(Language.Polish, "Ń", "N"),
            new LanguageDiacriticalMark(Language.Polish, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Polish, "Ś", "S"),
            new LanguageDiacriticalMark(Language.Polish, "Ż", "Z"),
            new LanguageDiacriticalMark(Language.Polish, "Ź", "Z"),
            // German 
            new LanguageDiacriticalMark(Language.German, "ä", "ae"),
            new LanguageDiacriticalMark(Language.German, "Ä", "oe"),
            new LanguageDiacriticalMark(Language.German, "ö", "ue"),
            new LanguageDiacriticalMark(Language.German, "Ö", "Ae"),
            new LanguageDiacriticalMark(Language.German, "ü", "Oe"),
            new LanguageDiacriticalMark(Language.German, "Ü", "Ue"),
            new LanguageDiacriticalMark(Language.German, "ß", "ss"),
            // French 
            new LanguageDiacriticalMark(Language.French, "à", "a"),
            new LanguageDiacriticalMark(Language.French, "À", "A"),
            new LanguageDiacriticalMark(Language.French, "â", "a"),
            new LanguageDiacriticalMark(Language.French, "Â", "A"),
            new LanguageDiacriticalMark(Language.French, "ç", "c"),
            new LanguageDiacriticalMark(Language.French, "Ç", "C"),
            new LanguageDiacriticalMark(Language.French, "é", "e"),
            new LanguageDiacriticalMark(Language.French, "É", "E"),
            new LanguageDiacriticalMark(Language.French, "è", "e"),
            new LanguageDiacriticalMark(Language.French, "È", "E"),
            new LanguageDiacriticalMark(Language.French, "ê", "e"),
            new LanguageDiacriticalMark(Language.French, "Ê", "E"),
            new LanguageDiacriticalMark(Language.French, "ë", "e"),
            new LanguageDiacriticalMark(Language.French, "Ë", "E"),
            new LanguageDiacriticalMark(Language.French, "î", "i"),
            new LanguageDiacriticalMark(Language.French, "Î", "I"),
            new LanguageDiacriticalMark(Language.French, "ï", "i"),
            new LanguageDiacriticalMark(Language.French, "Ï", "I"),
            new LanguageDiacriticalMark(Language.French, "ô", "o"),
            new LanguageDiacriticalMark(Language.French, "Ô", "O"),
            new LanguageDiacriticalMark(Language.French, "û", "u"),
            new LanguageDiacriticalMark(Language.French, "Û", "U"),
            new LanguageDiacriticalMark(Language.French, "ù", "u"),
            new LanguageDiacriticalMark(Language.French, "Ù", "U"),
            new LanguageDiacriticalMark(Language.French, "ü", "u"),
            new LanguageDiacriticalMark(Language.French, "Ü", "U"),
            new LanguageDiacriticalMark(Language.French, "ÿ", "y"),
            new LanguageDiacriticalMark(Language.French, "Ÿ", "Y"),
            new LanguageDiacriticalMark(Language.French, "œ", "oe"),
            new LanguageDiacriticalMark(Language.French, "Œ", "OE"),
            new LanguageDiacriticalMark(Language.French, "æ", "ae"),
            new LanguageDiacriticalMark(Language.French, "Æ", "AE"),
            // Spanish
            new LanguageDiacriticalMark(Language.Spanish, "á", "a"),
            new LanguageDiacriticalMark(Language.Spanish, "Á", "A"),
            new LanguageDiacriticalMark(Language.Spanish, "é", "e"),
            new LanguageDiacriticalMark(Language.Spanish, "É", "E"),
            new LanguageDiacriticalMark(Language.Spanish, "í", "i"),
            new LanguageDiacriticalMark(Language.Spanish, "Í", "I"),
            new LanguageDiacriticalMark(Language.Spanish, "ó", "o"),
            new LanguageDiacriticalMark(Language.Spanish, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Spanish, "ú", "u"),
            new LanguageDiacriticalMark(Language.Spanish, "Ú", "U"),
            new LanguageDiacriticalMark(Language.Spanish, "ü", "u"),
            new LanguageDiacriticalMark(Language.Spanish, "Ü", "U"),
            new LanguageDiacriticalMark(Language.Spanish, "ñ", "n"),
            new LanguageDiacriticalMark(Language.Spanish, "Ñ", "N"),
            // Swedish
            new LanguageDiacriticalMark(Language.Swedish, "å", "a"),
            new LanguageDiacriticalMark(Language.Swedish, "Å", "A"),
            new LanguageDiacriticalMark(Language.Swedish, "ä", "a"),
            new LanguageDiacriticalMark(Language.Swedish, "Ä", "A"),
            new LanguageDiacriticalMark(Language.Swedish, "ö", "o"),
            new LanguageDiacriticalMark(Language.Swedish, "Ö", "O"),
            // Slovak
            new LanguageDiacriticalMark(Language.Slovak, "á", "a"),
            new LanguageDiacriticalMark(Language.Slovak, "Á", "A"),
            new LanguageDiacriticalMark(Language.Slovak, "ä", "a"),
            new LanguageDiacriticalMark(Language.Slovak, "Ä", "A"),
            new LanguageDiacriticalMark(Language.Slovak, "č", "c"),
            new LanguageDiacriticalMark(Language.Slovak, "Č", "C"),
            new LanguageDiacriticalMark(Language.Slovak, "ď", "d"),
            new LanguageDiacriticalMark(Language.Slovak, "Ď", "D"),
            new LanguageDiacriticalMark(Language.Slovak, "é", "e"),
            new LanguageDiacriticalMark(Language.Slovak, "É", "E"),
            new LanguageDiacriticalMark(Language.Slovak, "í", "i"),
            new LanguageDiacriticalMark(Language.Slovak, "Í", "I"),
            new LanguageDiacriticalMark(Language.Slovak, "ĺ", "l"),
            new LanguageDiacriticalMark(Language.Slovak, "Ĺ", "L"),
            new LanguageDiacriticalMark(Language.Slovak, "ľ", "l"),
            new LanguageDiacriticalMark(Language.Slovak, "Ľ", "L"),
            new LanguageDiacriticalMark(Language.Slovak, "ň", "n"),
            new LanguageDiacriticalMark(Language.Slovak, "Ň", "N"),
            new LanguageDiacriticalMark(Language.Slovak, "ó", "o"),
            new LanguageDiacriticalMark(Language.Slovak, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Slovak, "ô", "o"),
            new LanguageDiacriticalMark(Language.Slovak, "Ô", "O"),
            new LanguageDiacriticalMark(Language.Slovak, "ŕ", "r"),
            new LanguageDiacriticalMark(Language.Slovak, "Ŕ", "R"),
            new LanguageDiacriticalMark(Language.Slovak, "š", "s"),
            new LanguageDiacriticalMark(Language.Slovak, "Š", "S"),
            new LanguageDiacriticalMark(Language.Slovak, "ť", "t"),
            new LanguageDiacriticalMark(Language.Slovak, "Ť", "T"),
            new LanguageDiacriticalMark(Language.Slovak, "ú", "u"),
            new LanguageDiacriticalMark(Language.Slovak, "Ú", "U"),
            new LanguageDiacriticalMark(Language.Slovak, "ý", "y"),
            new LanguageDiacriticalMark(Language.Slovak, "Ý", "Y"),
            new LanguageDiacriticalMark(Language.Slovak, "ž", "z"),
            new LanguageDiacriticalMark(Language.Slovak, "Ž", "Z"),
            // Czech 
            new LanguageDiacriticalMark(Language.Czech, "á", "a"),
            new LanguageDiacriticalMark(Language.Czech, "Á", "A"),
            new LanguageDiacriticalMark(Language.Czech, "č", "c"),
            new LanguageDiacriticalMark(Language.Czech, "Č", "C"),
            new LanguageDiacriticalMark(Language.Czech, "ď", "d"),
            new LanguageDiacriticalMark(Language.Czech, "Ď", "D"),
            new LanguageDiacriticalMark(Language.Czech, "é", "e"),
            new LanguageDiacriticalMark(Language.Czech, "É", "E"),
            new LanguageDiacriticalMark(Language.Czech, "ě", "e"),
            new LanguageDiacriticalMark(Language.Czech, "Ě", "E"),
            new LanguageDiacriticalMark(Language.Czech, "í", "i"),
            new LanguageDiacriticalMark(Language.Czech, "Í", "I"),
            new LanguageDiacriticalMark(Language.Czech, "ň", "n"),
            new LanguageDiacriticalMark(Language.Czech, "Ň", "N"),
            new LanguageDiacriticalMark(Language.Czech, "ó", "o"),
            new LanguageDiacriticalMark(Language.Czech, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Czech, "ř", "r"),
            new LanguageDiacriticalMark(Language.Czech, "Ř", "R"),
            new LanguageDiacriticalMark(Language.Czech, "š", "s"),
            new LanguageDiacriticalMark(Language.Czech, "Š", "S"),
            new LanguageDiacriticalMark(Language.Czech, "ť", "t"),
            new LanguageDiacriticalMark(Language.Czech, "Ť", "T"),
            new LanguageDiacriticalMark(Language.Czech, "ú", "u"),
            new LanguageDiacriticalMark(Language.Czech, "Ú", "U"),
            new LanguageDiacriticalMark(Language.Czech, "ů", "u"),
            new LanguageDiacriticalMark(Language.Czech, "Ů", "U"),
            new LanguageDiacriticalMark(Language.Czech, "ý", "y"),
            new LanguageDiacriticalMark(Language.Czech, "Ý", "Y"),
            new LanguageDiacriticalMark(Language.Czech, "ž", "z"),
            new LanguageDiacriticalMark(Language.Czech, "Ž", "Z"),
            // Hungarian
            new LanguageDiacriticalMark(Language.Hungarian, "á", "a"),
            new LanguageDiacriticalMark(Language.Hungarian, "Á", "A"),
            new LanguageDiacriticalMark(Language.Hungarian, "é", "e"),
            new LanguageDiacriticalMark(Language.Hungarian, "É", "E"),
            new LanguageDiacriticalMark(Language.Hungarian, "í", "i"),
            new LanguageDiacriticalMark(Language.Hungarian, "Í", "I"),
            new LanguageDiacriticalMark(Language.Hungarian, "ó", "o"),
            new LanguageDiacriticalMark(Language.Hungarian, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Hungarian, "ö", "o"),
            new LanguageDiacriticalMark(Language.Hungarian, "Ö", "O"),
            new LanguageDiacriticalMark(Language.Hungarian, "ő", "o"),
            new LanguageDiacriticalMark(Language.Hungarian, "Ő", "O"),
            new LanguageDiacriticalMark(Language.Hungarian, "ú", "u"),
            new LanguageDiacriticalMark(Language.Hungarian, "Ú", "U"),
            new LanguageDiacriticalMark(Language.Hungarian, "ü", "u"),
            new LanguageDiacriticalMark(Language.Hungarian, "Ü", "U"),
            new LanguageDiacriticalMark(Language.Hungarian, "ű", "u"),
            new LanguageDiacriticalMark(Language.Hungarian, "Ű", "U"),
            // Serbian (latinica)
            new LanguageDiacriticalMark(Language.Serbian, "č", "c"),
            new LanguageDiacriticalMark(Language.Serbian, "Č", "C"),
            new LanguageDiacriticalMark(Language.Serbian, "ć", "c"),
            new LanguageDiacriticalMark(Language.Serbian, "Ć", "C"),
            new LanguageDiacriticalMark(Language.Serbian, "đ", "d"),
            new LanguageDiacriticalMark(Language.Serbian, "Đ", "D"),
            new LanguageDiacriticalMark(Language.Serbian, "š", "s"),
            new LanguageDiacriticalMark(Language.Serbian, "Š", "S"),
            new LanguageDiacriticalMark(Language.Serbian, "ž", "z"),
            new LanguageDiacriticalMark(Language.Serbian, "Ž", "Z"),
            // Portuguese
            new LanguageDiacriticalMark(Language.Portuguese, "á", "a"),
            new LanguageDiacriticalMark(Language.Portuguese, "Á", "A"),
            new LanguageDiacriticalMark(Language.Portuguese, "à", "a"),
            new LanguageDiacriticalMark(Language.Portuguese, "À", "A"),
            new LanguageDiacriticalMark(Language.Portuguese, "â", "a"),
            new LanguageDiacriticalMark(Language.Portuguese, "Â", "A"),
            new LanguageDiacriticalMark(Language.Portuguese, "ã", "a"),
            new LanguageDiacriticalMark(Language.Portuguese, "Ã", "A"),
            new LanguageDiacriticalMark(Language.Portuguese, "é", "e"),
            new LanguageDiacriticalMark(Language.Portuguese, "É", "E"),
            new LanguageDiacriticalMark(Language.Portuguese, "ê", "e"),
            new LanguageDiacriticalMark(Language.Portuguese, "Ê", "E"),
            new LanguageDiacriticalMark(Language.Portuguese, "í", "i"),
            new LanguageDiacriticalMark(Language.Portuguese, "Í", "I"),
            new LanguageDiacriticalMark(Language.Portuguese, "ó", "o"),
            new LanguageDiacriticalMark(Language.Portuguese, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Portuguese, "ô", "o"),
            new LanguageDiacriticalMark(Language.Portuguese, "Ô", "O"),
            new LanguageDiacriticalMark(Language.Portuguese, "õ", "o"),
            new LanguageDiacriticalMark(Language.Portuguese, "Õ", "O"),
            new LanguageDiacriticalMark(Language.Portuguese, "ú", "u"),
            new LanguageDiacriticalMark(Language.Portuguese, "Ú", "U"),
            new LanguageDiacriticalMark(Language.Portuguese, "ç", "c"),
            new LanguageDiacriticalMark(Language.Portuguese, "Ç", "C"),
            // Italian
            new LanguageDiacriticalMark(Language.Italian, "à", "a"),
            new LanguageDiacriticalMark(Language.Italian, "À", "A"),
            new LanguageDiacriticalMark(Language.Italian, "è", "e"),
            new LanguageDiacriticalMark(Language.Italian, "È", "E"),
            new LanguageDiacriticalMark(Language.Italian, "é", "e"),
            new LanguageDiacriticalMark(Language.Italian, "É", "E"),
            new LanguageDiacriticalMark(Language.Italian, "ì", "i"),
            new LanguageDiacriticalMark(Language.Italian, "Ì", "I"),
            new LanguageDiacriticalMark(Language.Italian, "ò", "o"),
            new LanguageDiacriticalMark(Language.Italian, "Ò", "O"),
            new LanguageDiacriticalMark(Language.Italian, "ù", "u"),
            new LanguageDiacriticalMark(Language.Italian, "Ù", "U"),
            // Romanian
            new LanguageDiacriticalMark(Language.Romanian, "ă", "a"),
            new LanguageDiacriticalMark(Language.Romanian, "Ă", "A"),
            new LanguageDiacriticalMark(Language.Romanian, "â", "a"),
            new LanguageDiacriticalMark(Language.Romanian, "Â", "A"),
            new LanguageDiacriticalMark(Language.Romanian, "î", "i"),
            new LanguageDiacriticalMark(Language.Romanian, "Î", "I"),
            new LanguageDiacriticalMark(Language.Romanian, "ș", "s"),
            new LanguageDiacriticalMark(Language.Romanian, "Ș", "S"),
            new LanguageDiacriticalMark(Language.Romanian, "ț", "t"),
            new LanguageDiacriticalMark(Language.Romanian, "Ț", "T"),
            // Turkish
            new LanguageDiacriticalMark(Language.Turkish, "ç", "c"),
            new LanguageDiacriticalMark(Language.Turkish, "Ç", "C"),
            new LanguageDiacriticalMark(Language.Turkish, "ğ", "g"),
            new LanguageDiacriticalMark(Language.Turkish, "Ğ", "G"),
            new LanguageDiacriticalMark(Language.Turkish, "ı", "i"),
            new LanguageDiacriticalMark(Language.Turkish, "İ", "I"),
            new LanguageDiacriticalMark(Language.Turkish, "ö", "o"),
            new LanguageDiacriticalMark(Language.Turkish, "Ö", "O"),
            new LanguageDiacriticalMark(Language.Turkish, "ş", "s"),
            new LanguageDiacriticalMark(Language.Turkish, "Ş", "S"),
            new LanguageDiacriticalMark(Language.Turkish, "ü", "u"),
            new LanguageDiacriticalMark(Language.Turkish, "Ü", "U"),
            // Danish
            new LanguageDiacriticalMark(Language.Danish, "æ", "ae"),
            new LanguageDiacriticalMark(Language.Danish, "Æ", "AE"),
            new LanguageDiacriticalMark(Language.Danish, "ø", "o"),
            new LanguageDiacriticalMark(Language.Danish, "Ø", "O"),
            new LanguageDiacriticalMark(Language.Danish, "å", "a"),
            new LanguageDiacriticalMark(Language.Danish, "Å", "A"),
            // Norwegian
            new LanguageDiacriticalMark(Language.Norwegian, "æ", "ae"),
            new LanguageDiacriticalMark(Language.Norwegian, "Æ", "AE"),
            new LanguageDiacriticalMark(Language.Norwegian, "ø", "o"),
            new LanguageDiacriticalMark(Language.Norwegian, "Ø", "O"),
            new LanguageDiacriticalMark(Language.Norwegian, "å", "a"),
            new LanguageDiacriticalMark(Language.Norwegian, "Å", "A"),
            // Finnish
            new LanguageDiacriticalMark(Language.Finnish, "ä", "a"),
            new LanguageDiacriticalMark(Language.Finnish, "Ä", "A"),
            new LanguageDiacriticalMark(Language.Finnish, "ö", "o"),
            new LanguageDiacriticalMark(Language.Finnish, "Ö", "O"),
            // Icelandic
            new LanguageDiacriticalMark(Language.Icelandic, "á", "a"),
            new LanguageDiacriticalMark(Language.Icelandic, "Á", "A"),
            new LanguageDiacriticalMark(Language.Icelandic, "é", "e"),
            new LanguageDiacriticalMark(Language.Icelandic, "É", "E"),
            new LanguageDiacriticalMark(Language.Icelandic, "í", "i"),
            new LanguageDiacriticalMark(Language.Icelandic, "Í", "I"),
            new LanguageDiacriticalMark(Language.Icelandic, "ó", "o"),
            new LanguageDiacriticalMark(Language.Icelandic, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Icelandic, "ú", "u"),
            new LanguageDiacriticalMark(Language.Icelandic, "Ú", "U"),
            new LanguageDiacriticalMark(Language.Icelandic, "ý", "y"),
            new LanguageDiacriticalMark(Language.Icelandic, "Ý", "Y"),
            new LanguageDiacriticalMark(Language.Icelandic, "ð", "d"),
            new LanguageDiacriticalMark(Language.Icelandic, "Ð", "D"),
            new LanguageDiacriticalMark(Language.Icelandic, "þ", "th"),
            new LanguageDiacriticalMark(Language.Icelandic, "Þ", "Th"),
            new LanguageDiacriticalMark(Language.Icelandic, "æ", "ae"),
            new LanguageDiacriticalMark(Language.Icelandic, "Æ", "AE"),
            new LanguageDiacriticalMark(Language.Icelandic, "ö", "o"),
            new LanguageDiacriticalMark(Language.Icelandic, "Ö", "O"),
            // Croatian
            new LanguageDiacriticalMark(Language.Croatian, "č", "c"),
            new LanguageDiacriticalMark(Language.Croatian, "Č", "C"),
            new LanguageDiacriticalMark(Language.Croatian, "ć", "c"),
            new LanguageDiacriticalMark(Language.Croatian, "Ć", "C"),
            new LanguageDiacriticalMark(Language.Croatian, "đ", "d"),
            new LanguageDiacriticalMark(Language.Croatian, "Đ", "D"),
            new LanguageDiacriticalMark(Language.Croatian, "š", "s"),
            new LanguageDiacriticalMark(Language.Croatian, "Š", "S"),
            new LanguageDiacriticalMark(Language.Croatian, "ž", "z"),
            new LanguageDiacriticalMark(Language.Croatian, "Ž", "Z"),
            // Slovenian
            new LanguageDiacriticalMark(Language.Slovenian, "č", "c"),
            new LanguageDiacriticalMark(Language.Slovenian, "Č", "C"),
            new LanguageDiacriticalMark(Language.Slovenian, "š", "s"),
            new LanguageDiacriticalMark(Language.Slovenian, "Š", "S"),
            new LanguageDiacriticalMark(Language.Slovenian, "ž", "z"),
            new LanguageDiacriticalMark(Language.Slovenian, "Ž", "Z"),
            // Lithuanian
            new LanguageDiacriticalMark(Language.Lithuanian, "ą", "a"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Ą", "A"),
            new LanguageDiacriticalMark(Language.Lithuanian, "č", "c"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Č", "C"),
            new LanguageDiacriticalMark(Language.Lithuanian, "ę", "e"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Ę", "E"),
            new LanguageDiacriticalMark(Language.Lithuanian, "ė", "e"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Ė", "E"),
            new LanguageDiacriticalMark(Language.Lithuanian, "į", "i"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Į", "I"),
            new LanguageDiacriticalMark(Language.Lithuanian, "š", "s"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Š", "S"),
            new LanguageDiacriticalMark(Language.Lithuanian, "ų", "u"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Ų", "U"),
            new LanguageDiacriticalMark(Language.Lithuanian, "ū", "u"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Ū", "U"),
            new LanguageDiacriticalMark(Language.Lithuanian, "ž", "z"),
            new LanguageDiacriticalMark(Language.Lithuanian, "Ž", "Z"),
            // Latvian
            new LanguageDiacriticalMark(Language.Latvian, "ā", "a"),
            new LanguageDiacriticalMark(Language.Latvian, "Ā", "A"),
            new LanguageDiacriticalMark(Language.Latvian, "č", "c"),
            new LanguageDiacriticalMark(Language.Latvian, "Č", "C"),
            new LanguageDiacriticalMark(Language.Latvian, "ē", "e"),
            new LanguageDiacriticalMark(Language.Latvian, "Ē", "E"),
            new LanguageDiacriticalMark(Language.Latvian, "ģ", "g"),
            new LanguageDiacriticalMark(Language.Latvian, "Ģ", "G"),
            new LanguageDiacriticalMark(Language.Latvian, "ī", "i"),
            new LanguageDiacriticalMark(Language.Latvian, "Ī", "I"),
            new LanguageDiacriticalMark(Language.Latvian, "ķ", "k"),
            new LanguageDiacriticalMark(Language.Latvian, "Ķ", "K"),
            new LanguageDiacriticalMark(Language.Latvian, "ļ", "l"),
            new LanguageDiacriticalMark(Language.Latvian, "Ļ", "L"),
            new LanguageDiacriticalMark(Language.Latvian, "ņ", "n"),
            new LanguageDiacriticalMark(Language.Latvian, "Ņ", "N"),
            new LanguageDiacriticalMark(Language.Latvian, "š", "s"),
            new LanguageDiacriticalMark(Language.Latvian, "Š", "S"),
            new LanguageDiacriticalMark(Language.Latvian, "ū", "u"),
            new LanguageDiacriticalMark(Language.Latvian, "Ū", "U"),
            new LanguageDiacriticalMark(Language.Latvian, "ž", "z"),
            new LanguageDiacriticalMark(Language.Latvian, "Ž", "Z"),
            // Estonian
            new LanguageDiacriticalMark(Language.Estonian, "ä", "a"),
            new LanguageDiacriticalMark(Language.Estonian, "Ä", "A"),
            new LanguageDiacriticalMark(Language.Estonian, "ö", "o"),
            new LanguageDiacriticalMark(Language.Estonian, "Ö", "O"),
            new LanguageDiacriticalMark(Language.Estonian, "ü", "u"),
            new LanguageDiacriticalMark(Language.Estonian, "Ü", "U"),
            new LanguageDiacriticalMark(Language.Estonian, "õ", "o"),
            new LanguageDiacriticalMark(Language.Estonian, "Õ", "O"),
            // Catalan
            new LanguageDiacriticalMark(Language.Catalan, "à", "a"),
            new LanguageDiacriticalMark(Language.Catalan, "À", "A"),
            new LanguageDiacriticalMark(Language.Catalan, "é", "e"),
            new LanguageDiacriticalMark(Language.Catalan, "É", "E"),
            new LanguageDiacriticalMark(Language.Catalan, "è", "e"),
            new LanguageDiacriticalMark(Language.Catalan, "È", "E"),
            new LanguageDiacriticalMark(Language.Catalan, "í", "i"),
            new LanguageDiacriticalMark(Language.Catalan, "Í", "I"),
            new LanguageDiacriticalMark(Language.Catalan, "ï", "i"),
            new LanguageDiacriticalMark(Language.Catalan, "Ï", "I"),
            new LanguageDiacriticalMark(Language.Catalan, "ó", "o"),
            new LanguageDiacriticalMark(Language.Catalan, "Ó", "O"),
            new LanguageDiacriticalMark(Language.Catalan, "ò", "o"),
            new LanguageDiacriticalMark(Language.Catalan, "Ò", "O"),
            new LanguageDiacriticalMark(Language.Catalan, "ú", "u"),
            new LanguageDiacriticalMark(Language.Catalan, "Ú", "U"),
            new LanguageDiacriticalMark(Language.Catalan, "ü", "u"),
            new LanguageDiacriticalMark(Language.Catalan, "Ü", "U"),
            new LanguageDiacriticalMark(Language.Catalan, "ç", "c"),
            new LanguageDiacriticalMark(Language.Catalan, "Ç", "C"),
        };
    }
}