using System;
using System.Collections.Generic;
using System.Linq;
using Wookashi.ExtraText.Normalize.Enums;

namespace Wookashi.ExtraText.Normalize.Models
{
    internal sealed class LanguageDiacriticalMark
    {
        public Language Language { get; }
        public string Source { get; }
        public string Target { get; }

        private LanguageDiacriticalMark(Language language, string source, string target)
        {
            Language = language;
            Source = source;
            Target = target;
        }

        internal static readonly IReadOnlyList<LanguageDiacriticalMark> Marks = new List<LanguageDiacriticalMark>
        {
            // Polish
            new(Language.Polish, "ą", "a"),
            new(Language.Polish, "ć", "c"),
            new(Language.Polish, "ę", "e"),
            new(Language.Polish, "ł", "l"),
            new(Language.Polish, "ń", "n"),
            new(Language.Polish, "ó", "o"),
            new(Language.Polish, "ś", "s"),
            new(Language.Polish, "ź", "z"),
            new(Language.Polish, "ż", "z"),
            new(Language.Polish, "Ą", "A"),
            new(Language.Polish, "Ć", "C"),
            new(Language.Polish, "Ę", "E"),
            new(Language.Polish, "Ł", "L"),
            new(Language.Polish, "Ń", "N"),
            new(Language.Polish, "Ó", "O"),
            new(Language.Polish, "Ś", "S"),
            new(Language.Polish, "Ż", "Z"),
            new(Language.Polish, "Ź", "Z"),
            // German 
            new(Language.German, "ä", "ae"),
            new(Language.German, "Ä", "Ae"),
            new(Language.German, "ö", "oe"),
            new(Language.German, "Ö", "Oe"),
            new(Language.German, "ü", "ue"),
            new(Language.German, "Ü", "Ue"),
            new(Language.German, "ß", "ss"),
            // French 
            new(Language.French, "à", "a"),
            new(Language.French, "À", "A"),
            new(Language.French, "â", "a"),
            new(Language.French, "Â", "A"),
            new(Language.French, "ç", "c"),
            new(Language.French, "Ç", "C"),
            new(Language.French, "é", "e"),
            new(Language.French, "É", "E"),
            new(Language.French, "è", "e"),
            new(Language.French, "È", "E"),
            new(Language.French, "ê", "e"),
            new(Language.French, "Ê", "E"),
            new(Language.French, "ë", "e"),
            new(Language.French, "Ë", "E"),
            new(Language.French, "î", "i"),
            new(Language.French, "Î", "I"),
            new(Language.French, "ï", "i"),
            new(Language.French, "Ï", "I"),
            new(Language.French, "ô", "o"),
            new(Language.French, "Ô", "O"),
            new(Language.French, "û", "u"),
            new(Language.French, "Û", "U"),
            new(Language.French, "ù", "u"),
            new(Language.French, "Ù", "U"),
            new(Language.French, "ü", "u"),
            new(Language.French, "Ü", "U"),
            new(Language.French, "ÿ", "y"),
            new(Language.French, "Ÿ", "Y"),
            new(Language.French, "œ", "oe"),
            new(Language.French, "Œ", "OE"),
            new(Language.French, "æ", "ae"),
            new(Language.French, "Æ", "AE"),
            // Spanish
            new(Language.Spanish, "á", "a"),
            new(Language.Spanish, "Á", "A"),
            new(Language.Spanish, "é", "e"),
            new(Language.Spanish, "É", "E"),
            new(Language.Spanish, "í", "i"),
            new(Language.Spanish, "Í", "I"),
            new(Language.Spanish, "ó", "o"),
            new(Language.Spanish, "Ó", "O"),
            new(Language.Spanish, "ú", "u"),
            new(Language.Spanish, "Ú", "U"),
            new(Language.Spanish, "ü", "u"),
            new(Language.Spanish, "Ü", "U"),
            new(Language.Spanish, "ñ", "n"),
            new(Language.Spanish, "Ñ", "N"),
            // Swedish
            new(Language.Swedish, "å", "a"),
            new(Language.Swedish, "Å", "A"),
            new(Language.Swedish, "ä", "a"),
            new(Language.Swedish, "Ä", "A"),
            new(Language.Swedish, "ö", "o"),
            new(Language.Swedish, "Ö", "O"),
            // Slovak
            new(Language.Slovak, "á", "a"),
            new(Language.Slovak, "Á", "A"),
            new(Language.Slovak, "ä", "a"),
            new(Language.Slovak, "Ä", "A"),
            new(Language.Slovak, "č", "c"),
            new(Language.Slovak, "Č", "C"),
            new(Language.Slovak, "ď", "d"),
            new(Language.Slovak, "Ď", "D"),
            new(Language.Slovak, "é", "e"),
            new(Language.Slovak, "É", "E"),
            new(Language.Slovak, "í", "i"),
            new(Language.Slovak, "Í", "I"),
            new(Language.Slovak, "ĺ", "l"),
            new(Language.Slovak, "Ĺ", "L"),
            new(Language.Slovak, "ľ", "l"),
            new(Language.Slovak, "Ľ", "L"),
            new(Language.Slovak, "ň", "n"),
            new(Language.Slovak, "Ň", "N"),
            new(Language.Slovak, "ó", "o"),
            new(Language.Slovak, "Ó", "O"),
            new(Language.Slovak, "ô", "o"),
            new(Language.Slovak, "Ô", "O"),
            new(Language.Slovak, "ŕ", "r"),
            new(Language.Slovak, "Ŕ", "R"),
            new(Language.Slovak, "š", "s"),
            new(Language.Slovak, "Š", "S"),
            new(Language.Slovak, "ť", "t"),
            new(Language.Slovak, "Ť", "T"),
            new(Language.Slovak, "ú", "u"),
            new(Language.Slovak, "Ú", "U"),
            new(Language.Slovak, "ý", "y"),
            new(Language.Slovak, "Ý", "Y"),
            new(Language.Slovak, "ž", "z"),
            new(Language.Slovak, "Ž", "Z"),
            // Czech 
            new(Language.Czech, "á", "a"),
            new(Language.Czech, "Á", "A"),
            new(Language.Czech, "č", "c"),
            new(Language.Czech, "Č", "C"),
            new(Language.Czech, "ď", "d"),
            new(Language.Czech, "Ď", "D"),
            new(Language.Czech, "é", "e"),
            new(Language.Czech, "É", "E"),
            new(Language.Czech, "ě", "e"),
            new(Language.Czech, "Ě", "E"),
            new(Language.Czech, "í", "i"),
            new(Language.Czech, "Í", "I"),
            new(Language.Czech, "ň", "n"),
            new(Language.Czech, "Ň", "N"),
            new(Language.Czech, "ó", "o"),
            new(Language.Czech, "Ó", "O"),
            new(Language.Czech, "ř", "r"),
            new(Language.Czech, "Ř", "R"),
            new(Language.Czech, "š", "s"),
            new(Language.Czech, "Š", "S"),
            new(Language.Czech, "ť", "t"),
            new(Language.Czech, "Ť", "T"),
            new(Language.Czech, "ú", "u"),
            new(Language.Czech, "Ú", "U"),
            new(Language.Czech, "ů", "u"),
            new(Language.Czech, "Ů", "U"),
            new(Language.Czech, "ý", "y"),
            new(Language.Czech, "Ý", "Y"),
            new(Language.Czech, "ž", "z"),
            new(Language.Czech, "Ž", "Z"),
            // Hungarian
            new(Language.Hungarian, "á", "a"),
            new(Language.Hungarian, "Á", "A"),
            new(Language.Hungarian, "é", "e"),
            new(Language.Hungarian, "É", "E"),
            new(Language.Hungarian, "í", "i"),
            new(Language.Hungarian, "Í", "I"),
            new(Language.Hungarian, "ó", "o"),
            new(Language.Hungarian, "Ó", "O"),
            new(Language.Hungarian, "ö", "o"),
            new(Language.Hungarian, "Ö", "O"),
            new(Language.Hungarian, "ő", "o"),
            new(Language.Hungarian, "Ő", "O"),
            new(Language.Hungarian, "ú", "u"),
            new(Language.Hungarian, "Ú", "U"),
            new(Language.Hungarian, "ü", "u"),
            new(Language.Hungarian, "Ü", "U"),
            new(Language.Hungarian, "ű", "u"),
            new(Language.Hungarian, "Ű", "U"),
            // Serbian (latinica)
            new(Language.Serbian, "č", "c"),
            new(Language.Serbian, "Č", "C"),
            new(Language.Serbian, "ć", "c"),
            new(Language.Serbian, "Ć", "C"),
            new(Language.Serbian, "đ", "d"),
            new(Language.Serbian, "Đ", "D"),
            new(Language.Serbian, "š", "s"),
            new(Language.Serbian, "Š", "S"),
            new(Language.Serbian, "ž", "z"),
            new(Language.Serbian, "Ž", "Z"),
            // Portuguese
            new(Language.Portuguese, "á", "a"),
            new(Language.Portuguese, "Á", "A"),
            new(Language.Portuguese, "à", "a"),
            new(Language.Portuguese, "À", "A"),
            new(Language.Portuguese, "â", "a"),
            new(Language.Portuguese, "Â", "A"),
            new(Language.Portuguese, "ã", "a"),
            new(Language.Portuguese, "Ã", "A"),
            new(Language.Portuguese, "é", "e"),
            new(Language.Portuguese, "É", "E"),
            new(Language.Portuguese, "ê", "e"),
            new(Language.Portuguese, "Ê", "E"),
            new(Language.Portuguese, "í", "i"),
            new(Language.Portuguese, "Í", "I"),
            new(Language.Portuguese, "ó", "o"),
            new(Language.Portuguese, "Ó", "O"),
            new(Language.Portuguese, "ô", "o"),
            new(Language.Portuguese, "Ô", "O"),
            new(Language.Portuguese, "õ", "o"),
            new(Language.Portuguese, "Õ", "O"),
            new(Language.Portuguese, "ú", "u"),
            new(Language.Portuguese, "Ú", "U"),
            new(Language.Portuguese, "ç", "c"),
            new(Language.Portuguese, "Ç", "C"),
            // Italian
            new(Language.Italian, "à", "a"),
            new(Language.Italian, "À", "A"),
            new(Language.Italian, "è", "e"),
            new(Language.Italian, "È", "E"),
            new(Language.Italian, "é", "e"),
            new(Language.Italian, "É", "E"),
            new(Language.Italian, "ì", "i"),
            new(Language.Italian, "Ì", "I"),
            new(Language.Italian, "ò", "o"),
            new(Language.Italian, "Ò", "O"),
            new(Language.Italian, "ù", "u"),
            new(Language.Italian, "Ù", "U"),
            // Romanian
            new(Language.Romanian, "ă", "a"),
            new(Language.Romanian, "Ă", "A"),
            new(Language.Romanian, "â", "a"),
            new(Language.Romanian, "Â", "A"),
            new(Language.Romanian, "î", "i"),
            new(Language.Romanian, "Î", "I"),
            new(Language.Romanian, "ș", "s"),
            new(Language.Romanian, "Ș", "S"),
            new(Language.Romanian, "ț", "t"),
            new(Language.Romanian, "Ț", "T"),
            // Turkish
            new(Language.Turkish, "ç", "c"),
            new(Language.Turkish, "Ç", "C"),
            new(Language.Turkish, "ğ", "g"),
            new(Language.Turkish, "Ğ", "G"),
            new(Language.Turkish, "ı", "i"),
            new(Language.Turkish, "İ", "I"),
            new(Language.Turkish, "ö", "o"),
            new(Language.Turkish, "Ö", "O"),
            new(Language.Turkish, "ş", "s"),
            new(Language.Turkish, "Ş", "S"),
            new(Language.Turkish, "ü", "u"),
            new(Language.Turkish, "Ü", "U"),
            // Danish
            new(Language.Danish, "æ", "ae"),
            new(Language.Danish, "Æ", "AE"),
            new(Language.Danish, "ø", "o"),
            new(Language.Danish, "Ø", "O"),
            new(Language.Danish, "å", "a"),
            new(Language.Danish, "Å", "A"),
            // Norwegian
            new(Language.Norwegian, "æ", "ae"),
            new(Language.Norwegian, "Æ", "AE"),
            new(Language.Norwegian, "ø", "o"),
            new(Language.Norwegian, "Ø", "O"),
            new(Language.Norwegian, "å", "a"),
            new(Language.Norwegian, "Å", "A"),
            // Finnish
            new(Language.Finnish, "ä", "a"),
            new(Language.Finnish, "Ä", "A"),
            new(Language.Finnish, "ö", "o"),
            new(Language.Finnish, "Ö", "O"),
            // Icelandic
            new(Language.Icelandic, "á", "a"),
            new(Language.Icelandic, "Á", "A"),
            new(Language.Icelandic, "é", "e"),
            new(Language.Icelandic, "É", "E"),
            new(Language.Icelandic, "í", "i"),
            new(Language.Icelandic, "Í", "I"),
            new(Language.Icelandic, "ó", "o"),
            new(Language.Icelandic, "Ó", "O"),
            new(Language.Icelandic, "ú", "u"),
            new(Language.Icelandic, "Ú", "U"),
            new(Language.Icelandic, "ý", "y"),
            new(Language.Icelandic, "Ý", "Y"),
            new(Language.Icelandic, "ð", "d"),
            new(Language.Icelandic, "Ð", "D"),
            new(Language.Icelandic, "þ", "th"),
            new(Language.Icelandic, "Þ", "Th"),
            new(Language.Icelandic, "æ", "ae"),
            new(Language.Icelandic, "Æ", "AE"),
            new(Language.Icelandic, "ö", "o"),
            new(Language.Icelandic, "Ö", "O"),
            // Croatian
            new(Language.Croatian, "č", "c"),
            new(Language.Croatian, "Č", "C"),
            new(Language.Croatian, "ć", "c"),
            new(Language.Croatian, "Ć", "C"),
            new(Language.Croatian, "đ", "d"),
            new(Language.Croatian, "Đ", "D"),
            new(Language.Croatian, "š", "s"),
            new(Language.Croatian, "Š", "S"),
            new(Language.Croatian, "ž", "z"),
            new(Language.Croatian, "Ž", "Z"),
            // Slovenian
            new(Language.Slovenian, "č", "c"),
            new(Language.Slovenian, "Č", "C"),
            new(Language.Slovenian, "š", "s"),
            new(Language.Slovenian, "Š", "S"),
            new(Language.Slovenian, "ž", "z"),
            new(Language.Slovenian, "Ž", "Z"),
            // Lithuanian
            new(Language.Lithuanian, "ą", "a"),
            new(Language.Lithuanian, "Ą", "A"),
            new(Language.Lithuanian, "č", "c"),
            new(Language.Lithuanian, "Č", "C"),
            new(Language.Lithuanian, "ę", "e"),
            new(Language.Lithuanian, "Ę", "E"),
            new(Language.Lithuanian, "ė", "e"),
            new(Language.Lithuanian, "Ė", "E"),
            new(Language.Lithuanian, "į", "i"),
            new(Language.Lithuanian, "Į", "I"),
            new(Language.Lithuanian, "š", "s"),
            new(Language.Lithuanian, "Š", "S"),
            new(Language.Lithuanian, "ų", "u"),
            new(Language.Lithuanian, "Ų", "U"),
            new(Language.Lithuanian, "ū", "u"),
            new(Language.Lithuanian, "Ū", "U"),
            new(Language.Lithuanian, "ž", "z"),
            new(Language.Lithuanian, "Ž", "Z"),
            // Latvian
            new(Language.Latvian, "ā", "a"),
            new(Language.Latvian, "Ā", "A"),
            new(Language.Latvian, "č", "c"),
            new(Language.Latvian, "Č", "C"),
            new(Language.Latvian, "ē", "e"),
            new(Language.Latvian, "Ē", "E"),
            new(Language.Latvian, "ģ", "g"),
            new(Language.Latvian, "Ģ", "G"),
            new(Language.Latvian, "ī", "i"),
            new(Language.Latvian, "Ī", "I"),
            new(Language.Latvian, "ķ", "k"),
            new(Language.Latvian, "Ķ", "K"),
            new(Language.Latvian, "ļ", "l"),
            new(Language.Latvian, "Ļ", "L"),
            new(Language.Latvian, "ņ", "n"),
            new(Language.Latvian, "Ņ", "N"),
            new(Language.Latvian, "š", "s"),
            new(Language.Latvian, "Š", "S"),
            new(Language.Latvian, "ū", "u"),
            new(Language.Latvian, "Ū", "U"),
            new(Language.Latvian, "ž", "z"),
            new(Language.Latvian, "Ž", "Z"),
            // Estonian
            new(Language.Estonian, "ä", "a"),
            new(Language.Estonian, "Ä", "A"),
            new(Language.Estonian, "ö", "o"),
            new(Language.Estonian, "Ö", "O"),
            new(Language.Estonian, "ü", "u"),
            new(Language.Estonian, "Ü", "U"),
            new(Language.Estonian, "õ", "o"),
            new(Language.Estonian, "Õ", "O"),
            // Catalan
            new(Language.Catalan, "à", "a"),
            new(Language.Catalan, "À", "A"),
            new(Language.Catalan, "é", "e"),
            new(Language.Catalan, "É", "E"),
            new(Language.Catalan, "è", "e"),
            new(Language.Catalan, "È", "E"),
            new(Language.Catalan, "í", "i"),
            new(Language.Catalan, "Í", "I"),
            new(Language.Catalan, "ï", "i"),
            new(Language.Catalan, "Ï", "I"),
            new(Language.Catalan, "ó", "o"),
            new(Language.Catalan, "Ó", "O"),
            new(Language.Catalan, "ò", "o"),
            new(Language.Catalan, "Ò", "O"),
            new(Language.Catalan, "ú", "u"),
            new(Language.Catalan, "Ú", "U"),
            new(Language.Catalan, "ü", "u"),
            new(Language.Catalan, "Ü", "U"),
            new(Language.Catalan, "ç", "c"),
            new(Language.Catalan, "Ç", "C"),
            // Dutch
            new(Language.Dutch, "ë", "e"),
            new(Language.Dutch, "Ë", "E"),
            new(Language.Dutch, "ï", "i"),
            new(Language.Dutch, "Ï", "I"),
            new(Language.Dutch, "é", "e"),
            new(Language.Dutch, "É", "E"),
            new(Language.Dutch, "ü", "u"),
            new(Language.Dutch, "Ü", "U"),
            // Welsh
            new(Language.Welsh, "â", "a"),
            new(Language.Welsh, "Â", "A"),
            new(Language.Welsh, "ê", "e"),
            new(Language.Welsh, "Ê", "E"),
            new(Language.Welsh, "î", "i"),
            new(Language.Welsh, "Î", "I"),
            new(Language.Welsh, "ô", "o"),
            new(Language.Welsh, "Ô", "O"),
            new(Language.Welsh, "û", "u"),
            new(Language.Welsh, "Û", "U"),
            new(Language.Welsh, "ŵ", "w"),
            new(Language.Welsh, "Ŵ", "W"),
            new(Language.Welsh, "ŷ", "y"),
            new(Language.Welsh, "Ŷ", "Y"),
        };

        // A handful of characters are mapped differently across languages (e.g. German transliterates
        // ä/ö/ü as "ae"/"oe"/"ue", while every other language that has these letters maps them to a
        // single plain letter). For the language-agnostic overload we resolve each source character to
        // exactly one target - the shortest one - so the result is deterministic and independent of
        // declaration order above, instead of silently depending on whichever language happens to be
        // listed first in Marks. Language-specific overloads are unaffected and keep using Marks directly.
        internal static readonly IReadOnlyList<LanguageDiacriticalMark> CanonicalMarks = Marks
            .GroupBy(mark => mark.Source)
            .Select(group => group
                .OrderBy(mark => mark.Target.Length)
                .ThenBy(mark => mark.Target, StringComparer.Ordinal)
                .First())
            .ToList();

        // Groups Marks by language so ReplaceDiacriticalMarks(text, language) can look up the relevant
        // subset directly instead of linearly scanning and filtering the full list on every call.
        internal static readonly ILookup<Language, LanguageDiacriticalMark> ByLanguage =
            Marks.ToLookup(mark => mark.Language);
    }
}
